IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_Article_PersonId')
BEGIN
DROP INDEX [IX_Article_PersonId] ON [dbo].[Article]
END
GO
CREATE NONCLUSTERED INDEX [IX_Article_PersonId] ON [dbo].[Article]
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_CommentLike_CommentId')
BEGIN
DROP INDEX [IX_CommentLike_CommentId] ON [dbo].[CommentLike] WITH ( ONLINE = OFF )
END
GO
CREATE CLUSTERED INDEX [IX_CommentLike_CommentId] ON [dbo].[CommentLike]
(
	[CommentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_CommentLike_CommentId')
BEGIN
DROP INDEX [IX_CommentLike_PersonId] ON [dbo].[CommentLike]
END
GO
CREATE NONCLUSTERED INDEX [IX_CommentLike_PersonId] ON [dbo].[CommentLike]
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY]
GO


IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_Comment_ArticleId')
BEGIN
DROP INDEX [IX_Comment_ArticleId] ON [dbo].[Comment] WITH ( ONLINE = OFF )
END
GO
CREATE CLUSTERED INDEX [IX_Comment_ArticleId] ON [dbo].[Comment]
(
	[ArticleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_Article_PublishDate')
BEGIN
DROP INDEX [IX_Article_PublishDate] ON [dbo].[Article]
END
GO
CREATE NONCLUSTERED INDEX [IX_Article_PublishDate] ON [dbo].[Article]
(
	[PublishDate] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO